#!/usr/bin/sh
set -eu

# directory where the hook was triggered (your project)
CURRENT_DIRECTORY="$(pwd)"
# directory where the hook is running (your centralised hooks project)
GITHOOKS_DIRECTORY="$(dirname $(dirname $0))"
# get the dependency installation directory
CURRENT_BIN_DIRECTORY="$(githook-companion config dependency path)"
# where custom hook are located in other projects (see repo-specific-hooks example)
CUSTOM_GITHOOKS_DIRECTORY="$(githook-companion config hook path)"

# post-commit can enter a loop if you perform a commit in it
# using a lock is a workaround
LOCK=".git/post-commit.lock"

if [ ! -f "$LOCK" ]
then
echo "apply generic post-commit"
touch "$LOCK"

git add "CHANGELOG.md"

# --no-verifiy disables pre-commit, but not post-ommit : without a lock you get a loop
git commit --amend -C HEAD --no-verify

if [ -d "$CUSTOM_GITHOOKS_DIRECTORY" ] && [ -f "$CUSTOM_GITHOOKS_DIRECTORY/post-commit" ]
then
  echo "apply custom post-commit"
  "$CUSTOM_GITHOOKS_DIRECTORY"/post-commit
fi

rm "$LOCK"
fi
