#!/usr/bin/sh
set -eu

# directory where the hook was triggered (your project)
CURRENT_DIRECTORY="$(pwd)"
# directory where the hook is running (your centralised hooks project)
GITHOOKS_DIRECTORY="$(dirname $(dirname $0))"
# bin directory depending on OS and ARCH
GITHOOKS_BIN_DIRECTORY="$GITHOOKS_DIRECTORY/bin/$(uname -s)/$(uname -m)"
# where custom hook are located in other projects (see repo-specific-hooks example)
CUSTOM_GITHOOKS_DIRECTORY="$CURRENT_DIRECTORY/.githook-companion/hooks"
# you can have multiple changelog templates depending on the repo git server (GitHub, Azure DevOps, ...)
# look in the tool config directory .chglog
TEMPLATE_NAME=$("$GITHOOKS_BIN_DIRECTORY"/githook-companion-0-3-2 server name --default default)

echo "apply generic pre-commit"

# Make sure an email is set properly
if [ -z "$(git config user.email)" ]
then
	cat "\nError: user.email not set\n\n"
	exit 1
fi

# Make sure a name is set properly
if [ -z "$(git config user.name)" ]
then
	cat "\nError: user.name not set\n\n"
	exit 1
fi

# add the generated changelog to the commit
# with a git server provider specific template (or only a default)
git fetch origin --prune --tags
"$GITHOOKS_BIN_DIRECTORY"/git-chglog-0-15-4 \
    --next-tag 'Unreleased' \
    -o "$CURRENT_DIRECTORY/CHANGELOG.md" \
    -c "$GITHOOKS_DIRECTORY/.chglog/config.yml" \
    -t "$GITHOOKS_DIRECTORY/.chglog/templates/$TEMPLATE_NAME.tpl.md" 


# check for existing project specific hooks
if [ -d "$CUSTOM_GITHOOKS_DIRECTORY" ] && [ -f "$CUSTOM_GITHOOKS_DIRECTORY/pre-commit" ]
then
  echo "apply custom pre-commit"
  "$CUSTOM_GITHOOKS_DIRECTORY"/pre-commit
fi
