#!/usr/bin/sh
#; C:/Program\ Files/Git/usr/bin/sh.exe
set -eu

# directory where the hook was triggered (your project)
CURRENT_DIRECTORY="$(pwd)"
# directory where the hook is running (your centralised hooks project)
GITHOOKS_DIRECTORY="$(dirname $(dirname $0))"
# get the dependency installation directory
CURRENT_BIN_DIRECTORY="$(githook-companion config dependency path)"
# where child hook are located in other projects (see repo-specific-hooks example)
CUSTOM_GITHOOKS_DIRECTORY="$(githook-companion config hook path)"

echo "apply parent prepare-commit-msg"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

env > ~/githook-butler.log

# output githook-companion configuration
#"$GITHOOKS_BIN_DIRECTORY"/githook-companion-0-6-0 config show -c "$GITHOOKS_DIRECTORY"/.githook-companion/config.yaml

"$GITHOOKS_BIN_DIRECTORY"/githook-companion-0-6-0 commit validate -c "$GITHOOKS_DIRECTORY"/.githook-companion/config.yaml  -m "$(cat $COMMIT_MSG_FILE)" -o "$COMMIT_MSG_FILE" < /dev/tty
