#!/usr/bin/sh
#; C:/Program\ Files/Git/usr/bin/sh.exe
set -eu

# directory where the hook was triggered (your project)
CURRENT_DIRECTORY="$(pwd)"
# directory where the hook is running (your centralised hooks project)
GITHOOKS_DIRECTORY="$(dirname $(dirname $0))"
# bin directory depending on OS and ARCH
GITHOOKS_BIN_DIRECTORY="$GITHOOKS_DIRECTORY/bin/$(uname -s)/$(uname -m)"
# where custom hook are located in other projects (see repo-specific-hooks example)
CUSTOM_GITHOOKS_DIRECTORY="$CURRENT_DIRECTORY/.githook-companion/hooks"

echo "apply generic prepare-commit-msg"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

env > ~/githook-butler.log

# output githook-companion configuration
#"$GITHOOKS_BIN_DIRECTORY"/githook-companion-0-3-2 config show -c "$GITHOOKS_DIRECTORY"/.githook-companion/config.yaml

"$GITHOOKS_BIN_DIRECTORY"/githook-companion-0-3-2 commit validate -c "$GITHOOKS_DIRECTORY"/.githook-companion/config.yaml  -m "$(cat $COMMIT_MSG_FILE)" -o "$COMMIT_MSG_FILE" < /dev/tty
