#!/usr/bin/sh
set -eu

CURRENT_REPOSITORY="$(pwd)"
GITHOOKS_DIRECTORY="$(dirname $(dirname $(dirname $0)))"
GITHOOKS_BIN_DIRECTORY="$(githook-companion config dependency path)"
CUSTOM_GITHOOKS_DIRECTORY="$(githook-companion config hook path --child)"
TEMPLATE_NAME=$(githook-companion git server name --default default)
REPOSITORY_URL=$(githook-companion git server repository)

LOCK=".git/post-commit.lock"

if [ ! -f "$LOCK" ]
then
echo "apply generic post-commit"
touch "$LOCK"

# generating changelog
git fetch origin --prune --tags
"$GITHOOKS_BIN_DIRECTORY"/git-chglog \
    --next-tag 'Unreleased' \
    --repository-url "$REPOSITORY_URL" \
    -o "$CURRENT_REPOSITORY/CHANGELOG.md" \
    -c "$GITHOOKS_DIRECTORY/.chglog/config.yml" \
    -t "$GITHOOKS_DIRECTORY/.chglog/templates/$TEMPLATE_NAME.tpl.md" 

git add "CHANGELOG.md"

git commit --amend -C HEAD --no-verify

if [ -d "$CUSTOM_GITHOOKS_DIRECTORY" ] && [ -f "$CUSTOM_GITHOOKS_DIRECTORY/pre-commit" ] && [ "$GITHOOKS_DIRECTORY" != "$CURRENT_REPOSITORY" ]
then
  echo "apply custom post-commit"
  "$CUSTOM_GITHOOKS_DIRECTORY"/post-commit
fi

rm "$LOCK"
fi
