#!/usr/bin/sh
set -eu

CURRENT_DIRECTORY="$(pwd)"
CURRENT_BIN_DIRECTORY="$(githook-companion config dependency path)"

echo "child pre-commit"

# those are longer running tasks that will only be executed before pushing
"$CURRENT_BIN_DIRECTORY"/terraform init
"$CURRENT_BIN_DIRECTORY"/terraform validate

# do also the pre-commit tasks
./pre-commit
